cluster:
  name: ${CLUSTER_NAME}

# You want this node to only serve as a master: to not store any data and
# to have free resources. This will be the "coordinator" of your cluster.
node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

path:
  data: /data/data
  logs: /data/log
  plugins: /elasticsearch/plugins
  work: /data/work

bootstrap.mlockall: true

http.enabled: ${HTTP_ENABLE}

discovery.zen.ping.multicast.enabled: ${MULTICAST}
